# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luke Bearl
tagline:          'The blog of Luke Bearl'
description:      'I work as a full stack developer at <a href="http://www.transplantconnect.com" target="_blank">Transplant Connect</a>. This is my personal blog and the views expressed here are my own and may not reflect the views of my employer.'
url:              https://www.lukebearl.com
baseurl:          /

author:
  name:           'Luke Bearl'
  url:            https://twitter.com/lukebearl

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lbearl/lbearl.github.io

gems:
  - jekyll-gist
  - jekyll-paginate